/**
 * Localization. EN is the source of truth (the keys ARE the contract);
 * ZH mirrors it 1:1 — Record<MsgKey, string> forces completeness.
 * t() does %-style placeholder interpolation; bundle()/webviewL10nScript()
 * inject the catalog into webviews.
 */
import * as vscode from "vscode";

/** English catalog — keys are the contract; values are the default UI copy. */
export const EN = {
  "meta.lang": "en",

  "log.outputChannel": "Portal",
  "log.activating": "Portal {0} activating",
  "log.starting": "Starting Portal (provider={0})...",
  "log.cfQuickHttp2Fallback": "QUIC did not establish an Edge connection; retrying Quick Tunnel with HTTP/2...",
  "log.cfQuickReady": "Quick Tunnel Edge connection registered: {0}",
  "log.customStarting": "starting",
  "log.customAttach": "attach mode — adopting existing public URL {0}",
  "log.customReady": "custom tunnel ready: {0}",
  "log.mcpListening": "MCP server listening on http://127.0.0.1:{0}",
  "log.running": "Portal is running. Public URL: {0}",
  "log.agentReady": "Portal Agent terminal is ready — AI-run commands appear there.",
  "log.fileHttp": "File HTTP: {0}",
  "log.stopping": "Stopping Portal...",
  "log.stopped": "Stopped.",

  "err.noWorkspace": "Open a workspace folder before starting Portal.",
  "err.startFailed": "Start failed: {0}",
  "err.ngrokDomainRequired": "portal.ngrokDomain is required for the ngrok-reserved provider.",
  "err.ngrokNotInstalled": "ngrok is not installed. Run “Portal: Install/Upgrade ngrok” first.",
  "err.ngrokAuthInvalid": "ngrok authtoken is missing or invalid. Run: ngrok config add-authtoken <YOUR_TOKEN>",
  "err.ngrokDomainMissing": "ngrok reserved domain is required (portal.ngrokDomain).",
  "err.ngrokWinOnly": "ngrok auto-install currently supports Windows only.",
  "err.cfDomainRequired": "portal.cloudflareDomain is required for the cloudflare-named provider.",
  "err.cfHostnameInvalid": "Enter a valid Cloudflare public hostname such as bridge.example.com.",
  "err.cfTokenRequired": "Cloudflare Named Tunnel token is missing. Save it in the provider settings first.",
  "err.cfTokenInvalid": "The stored Cloudflare Tunnel token is malformed. Copy it again from the Cloudflare connector command.",
  "err.cfFixedPortRequired": "Cloudflare Named Tunnel requires a fixed local port (1-65535) matching its Cloudflare origin service.",
  "err.cfNotInstalled": "cloudflared is not installed. Run “Portal: Install cloudflared” first.",
  "err.cfInstallFailed": "cloudflared install failed. Install manually: https://github.com/cloudflare/cloudflared/releases",
  "err.cfWinOnly": "cloudflared auto-install currently supports Windows only.",
  "err.cfNamedTimeout": "cloudflared did not register a Named Tunnel connection within 30 seconds: {0}",
  "err.cfNamedNoOutput": "no connector output",
  "err.cfNamedExited": "cloudflared Named Tunnel stopped before it was ready: {0}",
  "err.cfNamedHealth": "The connector registered, but the public hostname did not reach the MCP server: {0}. Check Public Hostname and Origin Service settings.",
  "err.cfNoUrl": "cloudflared did not report a trycloudflare URL within 30s.",
  "err.cfQuickClashFakeIp": "Cloudflare Edge traffic was intercepted by Clash/Mihomo Fake-IP (198.18.0.0/15), and port 7844 failed. Put `+.argotunnel.com` in fake-ip-filter and route `*.argotunnel.com` DIRECT, or use a node that supports UDP and TCP 7844.",
  "err.cfQuickPort7844Blocked": "Cloudflare Edge is unreachable on outbound UDP/TCP port 7844. Allow port 7844 or use a compatible network/proxy.",
  "err.cfQuickProxyTls": "The HTTP/2 fallback reached a proxy/TUN endpoint, but the Cloudflare Edge TLS handshake was closed. Bypass proxy interception for `*.argotunnel.com`.",
  "err.cfQuickQuicFailed": "QUIC on UDP 7844 failed and the HTTP/2 fallback did not register a Cloudflare Edge connection.",
  "err.cfQuickNotReady": "Cloudflare issued a Quick Tunnel URL, but no Edge connection was registered: {0}",
  "err.customCommandRequired": "Set portal.customTunnelCommand, or portal.customTunnelUrl for attach mode, when the provider is custom.",
  "err.customBadPattern": "Invalid custom tunnel regex: {0}",
  "err.customUrlInvalid": "portal.customTunnelUrl must start with http:// or https://.",
  "err.customFailed": "Custom tunnel failed: {0}",
  "err.customTimeout": "The custom tunnel did not become ready within {0}: {1}",
  "err.tunnelExited": "The tunnel process exited unexpectedly ({0}).",
  "err.ngrokStartFailed": "ngrok failed to start the tunnel: {0}",
  "err.ngrokExited": "ngrok exited before the tunnel was ready ({0})",

  "adv.solutionPrefix": "Suggested fix:",
  "adv.docsPrefix": "More help:",
  "adv.ngrok334.title": "ngrok: this endpoint is already online (ERR_NGROK_334)",
  "adv.ngrok334.fix": "Another ngrok session is still holding this domain. Close the old session first — check dashboard.ngrok.com → Endpoints (or quit the other ngrok/Portal instance, e.g. a leftover process or another machine) — then start Portal again. To run both at once, enable portal.ngrokPoolingEnabled so Portal starts ngrok with --pooling-enabled and load balances the sessions.",
  "adv.ngrok320.title": "ngrok: this domain belongs to another account (ERR_NGROK_320)",
  "adv.ngrok320.fix": "The reserved domain is not on the account that issued the authtoken currently in use. Point portal.ngrokConfigPath (or the active profile\u2019s ngrok config file) at the config file of the account that owns this domain \u2014 or switch to a domain that account owns. Two windows only need two config files when their domains really live on two accounts.",
  "adv.ngrokAuth.title": "ngrok authtoken is missing or invalid",
  "adv.ngrokAuth.fix": "Run: ngrok config add-authtoken <YOUR_TOKEN> (copy the token from dashboard.ngrok.com → Your Authtoken), then start Portal again.",
  "adv.ngrokGeneric.title": "ngrok error {0}",
  "adv.ngrokGeneric.fix": "Open the official ngrok error page for the exact cause and step-by-step solutions.",
  "adv.cfToken.title": "Cloudflare rejected the Tunnel token",
  "adv.cfToken.fix": "The connector token is invalid or was refreshed in the dashboard. Copy the current token from Cloudflare Zero Trust → Networks → Tunnels and save it in the Portal provider settings, then start again.",
  "adv.cfAccess.title": "Cloudflare refused the tunnel connection",
  "adv.cfAccess.fix": "Cloudflare denied the connector (access denied). Verify that the tunnel still exists and that the token belongs to it, then retry. If your network is managed, also allow outbound TCP 7844.",
  "adv.cfQuick.title": "Cloudflare Quick Tunnel did not become ready",
  "adv.portBusy.title": "Local port is already in use",
  "adv.portBusy.fix": "The MCP server could not bind its local port. Stop the process occupying it, or set portal.localPort to another fixed port (0 = auto).",
  "adv.enoent.title": "Tunnel executable not found",
  "adv.enoent.fix": "The tunnel binary was not found on PATH. Install it via the Install buttons in Portal settings, or fix your PATH, then start again.",

  "provider.ngrok-reserved.name": "ngrok Reserved Domain",
  "provider.ngrok-reserved.desc": "Persistent URL via a reserved subdomain on ngrok.",
  "provider.ngrok-reserved.pickDesc": "Persistent URL via ngrok",
  "provider.cloudflare-quick.name": "Cloudflare Quick Tunnel",
  "provider.cloudflare-quick.desc": "No login or domain required. New random URL on every restart.",
  "provider.cloudflare-quick.pickDesc": "Random URL on every restart",
  "provider.cloudflare-named.name": "Cloudflare Named Tunnel",
  "provider.cloudflare-named.desc": "Persistent URL via a Cloudflare-managed hostname.",
  "provider.cloudflare-named.pickDesc": "Persistent URL via Cloudflare",
  "provider.custom.name": "Custom Tunnel",
  "provider.custom.desc": "Bring your own tunnel: run any client via a command template, or attach to an existing public URL.",
  "provider.custom.pickDesc": "Any tunnel client / attach to existing URL",

  "msg.copied": "Copied.",
  "msg.urlCopied": "Public URL copied to clipboard.",
  "msg.startFirst": "Start Portal first.",
  "msg.providerLocked": "Stop Portal before switching tunnel provider.",
  "msg.pickProvider": "Choose tunnel provider",
  "msg.ngrokDomainTitle": "ngrok reserved domain",
  "msg.routeTokenTitle": "MCP secret path (/mcp/<token>)",
  "msg.tokenReset": "MCP address regenerated. All clients using the old URL will stop working.",
  "msg.cfInstalled": "cloudflared installed.",
  "msg.ngrokInstalled": "ngrok installed. Now run: ngrok config add-authtoken <YOUR_TOKEN>",
  "msg.installFailed": "Install failed: {0}",
  "msg.cfTokenSaved": "Cloudflare Tunnel token saved securely.",
  "msg.cfTokenCleared": "Cloudflare Tunnel token removed.",
  "msg.cfTokenEmpty": "Paste a Cloudflare Tunnel token before saving.",
  "msg.noPrompts": "No prompt templates yet. Add one in Portal settings or via {0}.",
  "msg.pickPrompt": "Choose a prompt template to copy",
  "msg.promptCopied": "Prompt copied: {0}",
  "msg.promptSaved": "Prompt template saved.",
  "msg.promptDeleted": "Prompt template deleted: {0}",
  "msg.instructionsSaved": "Agent instructions saved.",

  "state.idle": "Idle",
  "state.starting": "Starting",
  "state.running": "Running",
  "state.error": "Error",

  "status.idle": "$(debug-disconnect) Portal: idle",
  "status.starting": "$(loading~spin) Portal: starting...",
  "status.running": "$(plug) Portal: {0} · :{1}",
  "status.error": "$(error) Portal: error",
  "status.tooltip.default": "Portal",
  "status.tooltip.idle": "Portal: not running. Click to open settings.",
  "status.tooltip.starting": "Starting tunnel ({0})...",
  "status.tooltip.running": "Running. Public URL: {0}\nLocal port: {1}\nClick to open settings.",
  "status.tooltip.error": "Portal error: {0}\nClick to open settings.",
  "status.tag.cloudflare-quick": "Cloudflare",
  "status.tag.cloudflare-named": "CF-Named",
  "status.tag.ngrok-reserved": "ngrok",
  "status.tag.custom": "Custom",

  "agent.terminalName": "Portal Agent",
  "agent.ready": "Portal Agent — commands from the connected AI appear here.",
  "agent.readonly": "(read-only — this terminal is driven by the AI)",
  "agent.exit": "exit {0}",
  "agent.timeout": "timeout",

  "activity.exit0": "exit 0",
  "activity.failed": "failed",
  "activity.ok": "done",
  "activity.started": "started {0}",
  "activity.polled": "read {0}",
  "activity.stoppedCmd": "stopped {0}",
  "activity.transferInfo": "file transfer info",

  "sidebar.title": "PORTAL",
  "sidebar.idle": "Idle",
  "sidebar.starting": "Starting",
  "sidebar.running": "Running",
  "sidebar.error": "Error",
  "sidebar.settings": "Settings",
  "sidebar.activeRequests": "Active requests",
  "sidebar.empty": "No activity yet.",
  "sidebar.emptyHint": "Tool calls will appear here.",
  "sidebar.session": "SESSION",
  "sidebar.start": "Start",
  "sidebar.stop": "Stop",
  "sidebar.connected": "Client connected",
  "sidebar.waiting": "Waiting for client…",
  "sidebar.stopped": "Stopped",
  "sidebar.stat.calls": "Calls",
  "sidebar.stat.avg": "Avg",
  "sidebar.stat.failures": "Failed",
  "sidebar.stat.success": "Success",
  "sidebar.footer.lastTool": "last: {0}",

  "settings.title": "Portal",
  "settings.heading": "Portal",
  "settings.notRunning": "Not running.",
  "settings.endpointOpen": "Endpoint open: {0}",
  "settings.endpointDown": "Endpoint is down.",
  "settings.errorPrefix": "Error: {0}",
  "settings.placeholderUrl": "public MCP URL appears here after start",
  "settings.copyUrl": "Copy URL",
  "settings.start": "Start",
  "settings.stop": "Stop",
  "settings.hintShare": "Share the URL with an MCP client. It embeds the secret route token — treat it like a password.",
  "settings.section.connection": "Connection",
  "settings.section.tools": "Tools",
  "settings.section.security": "Security",
  "settings.section.diagnostics": "Diagnostics",
  "settings.tunnelMode": "Tunnel provider",
  "settings.ngrokDomain": "ngrok reserved domain",
  "settings.ngrokPoolingEnabled": "Enable ngrok load balancing (--pooling-enabled)",
  "settings.ngrokPoolingHint": "Use only when multiple Portal/ngrok sessions intentionally share the same reserved domain. It allows ngrok to route traffic across those sessions instead of raising ERR_NGROK_334.",
  "settings.cfHostname": "Cloudflare hostname",
  "settings.cfTunnelToken": "Cloudflare Tunnel token (stored securely)",
  "settings.cfTokenPlaceholder": "paste tunnel token",
  "settings.cfTokenStored": "Token saved.",
  "settings.cfTokenMissing": "No token saved.",
  "settings.saveSecret": "Save",
  "settings.clearSecret": "Clear",
  "settings.cfFixedPortHint": "Named Tunnel requires a fixed local port that matches the Cloudflare origin service.",
  "settings.customCommand": "Custom tunnel command",
  "settings.customUrl": "Custom public URL (attach mode)",
  "settings.customHint": "Placeholders: {{port}} {{token}} {{workspace}}. Leave the command empty with a URL set to attach to an existing tunnel.",
  "settings.secretPath": "Route token (/mcp/<token>)",
  "settings.localPort": "Local port (0 = auto)",
  "settings.autoStart": "Start automatically when a workspace opens",
  "settings.showTerm": "Mirror commands into the Portal Agent terminal",
  "settings.tunnelStatus": "Tunnel binaries",
  "settings.detecting": "Detecting…",
  "settings.detected": "Detected.",
  "settings.notDetected": "Not probed yet.",
  "settings.recheck": "Re-check",
  "settings.notInstalled": "not installed",
  "settings.install": "Install",
  "settings.reinstall": "Reinstall",
  "settings.authtokenMissing": "authtoken missing",
  "settings.cfNamedConfig": "Named tunnel config",
  "settings.configReady": "ready",
  "settings.openLog": "Open log",
  "settings.resetAddress": "Regenerate address",
  "settings.resetHint": "Invalidates the current URL; all clients must be updated.",
  "settings.toolsHint": "Portal deliberately exposes only commands and file transfer.",
  "settings.openVscodeSettings": "Open VS Code settings",
  "settings.settingsHint": "All options live under the portal.* section.",
  "settings.copyInstall": "Copy",

  "settings.ngrokConfigPath": "ngrok config file (--config)",
  "settings.ngrokConfigPathHint": "Path to an ngrok agent config file. Point each window at a different file to run two ngrok accounts side by side.",
  "settings.ngrokApiPort": "ngrok inspection port to poll",
  "settings.ngrokApiPortHint": "Which local port Portal asks for the tunnel list. Concurrent ngrok agents cannot share a port — the second one silently moves to 4041, so point the second window at 4041 to skip the wait. 0 = scan 4040-4045 and match by domain.",

  "profile.sectionTitle": "Connection profiles",
  "profile.hint": "A profile bundles the tunnel provider, domain and ngrok account. The list is shared globally; the selected profile is stored in this workspace, so several VS Code windows can run different profiles at the same time.",
  "profile.empty": "No profiles yet — click “New profile” to create one.",
  "profile.new": "New profile",
  "profile.nameLabel": "Profile name",
  "profile.namePlaceholder": "e.g. ngrok account A",
  "profile.save": "Save",
  "profile.cancel": "Cancel",
  "profile.edit": "Edit",
  "profile.duplicate": "Duplicate",
  "profile.delete": "Delete",
  "profile.use": "Use",
  "profile.activeTag": "active in this workspace",
  "profile.editorTitle": "Edit profile",
  "profile.newTitle": "New profile",
  "profile.defaultOption": "None — plain settings",
  "profile.pickPlaceholder": "Select a connection profile",
  "profile.noneDefined": "No connection profiles defined yet.",
  "profile.saved": "Profile “{0}” saved.",
  "profile.deleted": "Profile “{0}” deleted.",
  "profile.duplicated": "Profile duplicated as “{0}”.",
  "profile.nameRequired": "A profile name is required.",
  "profile.nameDuplicate": "A profile with that name already exists.",
  "profile.switched": "Active profile: {0}",
  "profile.switchedRestart": "Switched to “{0}”. Restart Portal to apply it.",
  "profile.restartNow": "Restart now",
  "profile.noFolder": "No workspace folder is open, so the selection was saved globally and applies to every window.",
  "profile.runningAs": "profile {0}",
  "profile.runningDefault": "default settings",
  "profile.stale": "Running on “{0}”; “{1}” is selected — restart to apply.",

  "command.switchProfile": "Portal: Switch connection profile...",
  "command.restart": "Portal: Restart",
  "sidebar.profile": "Profile",

  "sidebar.sessionPick": "Select which MCP session the sidebar shows",

  "session.sectionTitle": "MCP sessions",
  "session.hint": "Every session is an independent MCP endpoint with its own route token, and optionally its own workspace and tunnel settings. Sessions run in parallel; the sidebar picks which one is displayed.",
  "session.empty": "No sessions yet \u2014 click \u201cNew session\u201d to create one.",
  "session.new": "New session",
  "session.idLabel": "Session id",
  "session.labelLabel": "Display label",
  "session.tokenLabel": "Route token",
  "session.tokenPlaceholder": "leave empty to auto-generate",
  "session.workspaceLabel": "Workspace path (optional)",
  "session.editorTitle": "Edit session",
  "session.newTitle": "New session",
  "session.saved": "Session \u201c{0}\u201d saved.",
  "session.deleted": "Session \u201c{0}\u201d deleted.",
  "session.idRequired": "A session id is required.",
  "session.idDuplicate": "A session with that id already exists.",
  "session.defaultLabel": "default",

  "msg.pickToken": "Select an MCP session",
  "msg.tokenLabelTitle": "Session label",
  "msg.tokenLabelPlaceholder": "e.g. workspace-a",
  "msg.pickTokenRemove": "Select a session to remove",
  "msg.tokenAdded": "Portal: added session \u201c{0}\u201d.",

  "settings.section.agentInstructions": "Agent instructions",
  "settings.agentInstructionsHint": "Returned to MCP clients during `initialize`. Leave empty to use Portal's built-in default instructions. Applies on the next start of Portal.",
  "settings.agentInstructionsPlaceholder": "Leave empty to use Portal's built-in default instructions.",
  "settings.saveInstructions": "Save",

  "prompt.sectionTitle": "Prompts",
  "prompt.hint": "Pre-author prompts that contain your link: use {url} as the placeholder — it is replaced with the live public MCP URL when copied.",
  "prompt.nameLabel": "Name",
  "prompt.templateLabel": "Template",
  "prompt.namePlaceholder": "e.g. Kick-off prompt for agents",
  "prompt.templatePlaceholder": "Connect to the MCP endpoint at {url} and ...",
  "prompt.add": "Add",
  "prompt.update": "Update",
  "prompt.cancel": "Cancel",
  "prompt.copy": "Copy",
  "prompt.edit": "Edit",
  "prompt.delete": "Delete",
  "prompt.empty": "No prompt templates yet.",
  "prompt.copyTip": "Copy with live URL",
  "prompt.needsUrl": "Contains {url} — available after start",
  "prompt.staticTip": "Copy as-is (no URL placeholder)",

  "advice.openDocs": "Open docs",
  "advice.copySolution": "Copy fix",
  "advice.solution": "Fix",
};

export type MsgKey = keyof typeof EN;

/** Chinese catalog — must mirror EN 1:1. */
export const ZH: Record<MsgKey, string> = {
  "meta.lang": "zh-CN",

  "log.outputChannel": "Portal",
  "log.activating": "Portal {0} 正在激活",
  "log.starting": "正在启动 Portal（provider={0}）...",
  "log.cfQuickHttp2Fallback": "QUIC 未能建立 Edge 连接，正在使用 HTTP/2 重试快速隧道...",
  "log.cfQuickReady": "快速隧道 Edge 连接已注册：{0}",
  "log.customStarting": "正在启动",
  "log.customAttach": "挂接模式 — 直接采用现有公开地址 {0}",
  "log.customReady": "自定义隧道已就绪：{0}",
  "log.mcpListening": "MCP 服务监听 http://127.0.0.1:{0}",
  "log.running": "Portal 已运行。公开地址：{0}",
  "log.agentReady": "Portal Agent 终端已就绪 — AI 执行的命令会显示在那里。",
  "log.fileHttp": "文件 HTTP：{0}",
  "log.stopping": "正在停止 Portal...",
  "log.stopped": "已停止。",

  "err.noWorkspace": "启动 Portal 前请先打开一个工作区文件夹。",
  "err.startFailed": "启动失败：{0}",
  "err.ngrokDomainRequired": "使用 ngrok-reserved 时必须填写 portal.ngrokDomain。",
  "err.ngrokNotInstalled": "未安装 ngrok。请先运行「Portal：安装/升级 ngrok」。",
  "err.ngrokAuthInvalid": "ngrok authtoken 缺失或无效。请运行：ngrok config add-authtoken <YOUR_TOKEN>",
  "err.ngrokDomainMissing": "需要 ngrok 预留域名（portal.ngrokDomain）。",
  "err.ngrokWinOnly": "ngrok 自动安装目前仅支持 Windows。",
  "err.cfDomainRequired": "使用 cloudflare-named 时必须填写 portal.cloudflareDomain。",
  "err.cfHostnameInvalid": "请输入有效的 Cloudflare 公开主机名，例如 bridge.example.com。",
  "err.cfTokenRequired": "缺少 Cloudflare Named Tunnel Token。请先在提供方设置中安全保存 Token。",
  "err.cfTokenInvalid": "保存的 Cloudflare Tunnel Token 格式异常，请从 Cloudflare Connector 命令重新复制。",
  "err.cfFixedPortRequired": "Cloudflare 命名隧道必须使用 1-65535 的固定本地端口，并与 Cloudflare Origin Service 一致。",
  "err.cfNotInstalled": "未安装 cloudflared。请先运行「Portal：安装 cloudflared」。",
  "err.cfInstallFailed": "cloudflared 安装失败。请手动安装：https://github.com/cloudflare/cloudflared/releases",
  "err.cfWinOnly": "cloudflared 自动安装目前仅支持 Windows。",
  "err.cfNamedTimeout": "cloudflared 在 30 秒内未注册命名隧道连接：{0}",
  "err.cfNamedNoOutput": "没有 Connector 输出",
  "err.cfNamedExited": "cloudflared 命名隧道尚未就绪便已停止：{0}",
  "err.cfNamedHealth": "Connector 已注册，但公开主机名未连接到 MCP 服务：{0}。请检查 Public Hostname 和 Origin Service 设置。",
  "err.cfNoUrl": "cloudflared 在 30 秒内未返回 trycloudflare 地址。",
  "err.cfQuickClashFakeIp": "Cloudflare Edge 流量被 Clash/Mihomo Fake-IP（198.18.0.0/15）接管，且 7844 端口连接失败。请把 `+.argotunnel.com` 加入 fake-ip-filter，并将 `*.argotunnel.com` 设为 DIRECT；或改用同时支持 UDP/TCP 7844 的节点。",
  "err.cfQuickPort7844Blocked": "无法通过出站 UDP/TCP 7844 连接 Cloudflare Edge。请放行 7844 端口，或使用兼容的网络/代理。",
  "err.cfQuickProxyTls": "HTTP/2 回退已连接到代理/TUN 端点，但 Cloudflare Edge TLS 握手被关闭。请让 `*.argotunnel.com` 绕过代理拦截。",
  "err.cfQuickQuicFailed": "UDP 7844 上的 QUIC 失败，HTTP/2 回退也未能注册 Cloudflare Edge 连接。",
  "err.cfQuickNotReady": "Cloudflare 已分配快速隧道地址，但未注册 Edge 连接：{0}",
  "err.customCommandRequired": "提供方为 custom 时，需设置 portal.customTunnelCommand，或设置 customTunnelUrl 进入挂接模式。",
  "err.customBadPattern": "自定义隧道正则无效：{0}",
  "err.customUrlInvalid": "portal.customTunnelUrl 必须以 http:// 或 https:// 开头。",
  "err.customFailed": "自定义隧道失败：{0}",
  "err.customTimeout": "自定义隧道在 {0} 内未就绪：{1}",
  "err.tunnelExited": "隧道进程意外退出（{0}）。",
  "err.ngrokStartFailed": "ngrok 启动隧道失败：{0}",
  "err.ngrokExited": "ngrok 在隧道就绪前退出（{0}）",

  "adv.solutionPrefix": "建议修复：",
  "adv.docsPrefix": "更多帮助：",
  "adv.ngrok334.title": "ngrok：该端点已在线（ERR_NGROK_334）",
  "adv.ngrok334.fix": "另一个 ngrok 会话仍占用此域名。请先关闭旧会话——查看 dashboard.ngrok.com → Endpoints（或退出另一个 ngrok/Portal 实例，例如残留进程或另一台机器）——再重新启动 Portal。若要两者同时运行，请启用 portal.ngrokPoolingEnabled，让 Portal 使用 --pooling-enabled 启动 ngrok 并进行负载均衡。",
  "adv.ngrok320.title": "ngrok：该域名属于另一个账号（ERR_NGROK_320）",
  "adv.ngrok320.fix": "这个预留域名不在当前 authtoken 所属账号名下。请把 portal.ngrokConfigPath（或当前档案的 ngrok 配置文件）指向拥有该域名的那个账号的配置文件，或改用该账号名下的域名。只有当两个域名确实分属两个账号时，两个窗口才需要各自的配置文件。",
  "adv.ngrokAuth.title": "ngrok authtoken 缺失或无效",
  "adv.ngrokAuth.fix": "运行：ngrok config add-authtoken <你的Token>（在 dashboard.ngrok.com → Your Authtoken 复制），然后重新启动 Portal。",
  "adv.ngrokGeneric.title": "ngrok 错误 {0}",
  "adv.ngrokGeneric.fix": "打开 ngrok 官方错误页面查看具体原因与分步解决方案。",
  "adv.cfToken.title": "Cloudflare 拒绝了 Tunnel Token",
  "adv.cfToken.fix": "连接器 Token 无效或已在控制台刷新。请从 Cloudflare Zero Trust → Networks → Tunnels 复制当前 Token，保存到 Portal 提供方设置后重试。",
  "adv.cfAccess.title": "Cloudflare 拒绝了隧道连接",
  "adv.cfAccess.fix": "Cloudflare 拒绝了连接器（Access denied）。请确认隧道仍存在且 Token 属于它，然后重试；受管网络还需放行出站 TCP 7844。",
  "adv.cfQuick.title": "Cloudflare Quick Tunnel 未能就绪",
  "adv.portBusy.title": "本地端口已被占用",
  "adv.portBusy.fix": "MCP 服务器无法绑定本地端口。请停止占用该端口的进程，或将 portal.localPort 改为其他固定端口（0 = 自动）。",
  "adv.enoent.title": "找不到隧道可执行文件",
  "adv.enoent.fix": "PATH 中找不到隧道程序。请通过 Portal 设置中的安装按钮安装，或修正 PATH 后重试。",

  "provider.ngrok-reserved.name": "ngrok 预留域名",
  "provider.ngrok-reserved.desc": "通过 ngrok 预留子域名提供固定地址。",
  "provider.ngrok-reserved.pickDesc": "通过 ngrok 固定地址",
  "provider.cloudflare-quick.name": "Cloudflare 快速隧道",
  "provider.cloudflare-quick.desc": "无需登录或域名。每次重启都会得到新的随机地址。",
  "provider.cloudflare-quick.pickDesc": "每次重启随机地址",
  "provider.cloudflare-named.name": "Cloudflare 命名隧道",
  "provider.cloudflare-named.desc": "通过 Cloudflare 托管主机名提供固定地址。",
  "provider.cloudflare-named.pickDesc": "通过 Cloudflare 固定地址",
  "provider.custom.name": "自定义隧道",
  "provider.custom.desc": "自带隧道：用命令模板运行任意客户端，或挂接现有公开地址。",
  "provider.custom.pickDesc": "任意客户端 / 挂接现有地址",

  "msg.copied": "已复制。",
  "msg.urlCopied": "公开 URL 已复制到剪贴板。",
  "msg.startFirst": "请先启动 Portal。",
  "msg.providerLocked": "切换隧道提供方前请先停止 Portal。",
  "msg.pickProvider": "选择隧道提供方",
  "msg.ngrokDomainTitle": "ngrok 预留域名",
  "msg.routeTokenTitle": "MCP 秘密路径（/mcp/<token>）",
  "msg.tokenReset": "MCP 地址已重新生成。使用旧 URL 的客户端将全部失效。",
  "msg.cfInstalled": "cloudflared 已安装。",
  "msg.ngrokInstalled": "ngrok 已安装。请运行：ngrok config add-authtoken <YOUR_TOKEN>",
  "msg.installFailed": "安装失败：{0}",
  "msg.cfTokenSaved": "Cloudflare Tunnel Token 已安全保存。",
  "msg.cfTokenCleared": "Cloudflare Tunnel Token 已移除。",
  "msg.cfTokenEmpty": "请先粘贴 Cloudflare Tunnel Token 再保存。",
  "msg.noPrompts": "还没有提示词模板。请在 Portal 设置中添加，或使用 {0}。",
  "msg.pickPrompt": "选择要复制的提示词模板",
  "msg.promptCopied": "提示词已复制：{0}",
  "msg.promptSaved": "提示词模板已保存。",
  "msg.promptDeleted": "提示词模板已删除：{0}",
  "msg.instructionsSaved": "Agent 提示词已保存。",

  "state.idle": "空闲",
  "state.starting": "启动中",
  "state.running": "运行中",
  "state.error": "错误",

  "status.idle": "$(debug-disconnect) Portal：空闲",
  "status.starting": "$(loading~spin) Portal：启动中...",
  "status.running": "$(plug) Portal：{0} · :{1}",
  "status.error": "$(error) Portal：错误",
  "status.tooltip.default": "Portal",
  "status.tooltip.idle": "Portal：未运行。点击打开设置。",
  "status.tooltip.starting": "正在启动隧道（{0}）...",
  "status.tooltip.running": "运行中。公开地址：{0}\n本地端口：{1}\n点击打开设置。",
  "status.tooltip.error": "Portal 错误：{0}\n点击打开设置。",
  "status.tag.cloudflare-quick": "Cloudflare",
  "status.tag.cloudflare-named": "CF 命名",
  "status.tag.ngrok-reserved": "ngrok",
  "status.tag.custom": "自定义",

  "agent.terminalName": "Portal Agent",
  "agent.ready": "Portal Agent — 已连接 AI 执行的命令会显示在这里。",
  "agent.readonly": "（只读 — 此终端由 AI 驱动）",
  "agent.exit": "退出 {0}",
  "agent.timeout": "超时",

  "activity.exit0": "退出 0",
  "activity.failed": "失败",
  "activity.ok": "完成",
  "activity.started": "已启动 {0}",
  "activity.polled": "读取 {0}",
  "activity.stoppedCmd": "停止 {0}",
  "activity.transferInfo": "文件传输信息",

  "sidebar.title": "PORTAL",
  "sidebar.idle": "空闲",
  "sidebar.starting": "启动中",
  "sidebar.running": "运行中",
  "sidebar.error": "错误",
  "sidebar.settings": "设置",
  "sidebar.activeRequests": "活动请求数",
  "sidebar.empty": "暂无活动。",
  "sidebar.emptyHint": "工具调用会显示在这里。",
  "sidebar.session": "会话",
  "sidebar.start": "启动",
  "sidebar.stop": "停止",
  "sidebar.connected": "客户端已连接",
  "sidebar.waiting": "等待客户端连接…",
  "sidebar.stopped": "已停止",
  "sidebar.stat.calls": "调用",
  "sidebar.stat.avg": "平均",
  "sidebar.stat.failures": "失败",
  "sidebar.stat.success": "成功率",
  "sidebar.footer.lastTool": "最近：{0}",

  "settings.title": "Portal",
  "settings.heading": "Portal",
  "settings.notRunning": "未运行。",
  "settings.endpointOpen": "端点已开放：{0}",
  "settings.endpointDown": "端点未开放。",
  "settings.errorPrefix": "错误：{0}",
  "settings.placeholderUrl": "启动后公开 MCP URL 显示在这里",
  "settings.copyUrl": "复制 URL",
  "settings.start": "启动",
  "settings.stop": "停止",
  "settings.hintShare": "把 URL 分享给 MCP 客户端。URL 内嵌秘密路由令牌——请像密码一样保管。",
  "settings.section.connection": "连接",
  "settings.section.tools": "工具",
  "settings.section.security": "安全",
  "settings.section.diagnostics": "诊断",
  "settings.tunnelMode": "隧道提供方",
  "settings.ngrokDomain": "ngrok 预留域名",
  "settings.ngrokPoolingEnabled": "启用 ngrok 负载均衡（--pooling-enabled）",
  "settings.ngrokPoolingHint": "仅在多个 Portal/ngrok 会话有意共用同一预留域名时使用。它允许 ngrok 在这些会话间分流，而不是报 ERR_NGROK_334。",
  "settings.cfHostname": "Cloudflare 主机名",
  "settings.cfTunnelToken": "Cloudflare Tunnel Token（安全保存）",
  "settings.cfTokenPlaceholder": "粘贴 Tunnel Token",
  "settings.cfTokenStored": "Token 已保存。",
  "settings.cfTokenMissing": "未保存 Token。",
  "settings.saveSecret": "保存",
  "settings.clearSecret": "清除",
  "settings.cfFixedPortHint": "命名隧道必须使用与 Cloudflare Origin Service 一致的固定本地端口。",
  "settings.customCommand": "自定义隧道命令",
  "settings.customUrl": "自定义公开 URL（挂接模式）",
  "settings.customHint": "占位符：{{port}} {{token}} {{workspace}}。命令留空且填写 URL 时，直接挂接现有隧道。",
  "settings.secretPath": "路由令牌（/mcp/<token>）",
  "settings.localPort": "本地端口（0 = 自动）",
  "settings.autoStart": "打开工作区时自动启动",
  "settings.showTerm": "命令镜像到 Portal Agent 终端",
  "settings.tunnelStatus": "隧道工具",
  "settings.detecting": "检测中…",
  "settings.detected": "已检测。",
  "settings.notDetected": "尚未检测。",
  "settings.recheck": "重新检测",
  "settings.notInstalled": "未安装",
  "settings.install": "安装",
  "settings.reinstall": "重新安装",
  "settings.authtokenMissing": "缺少 authtoken",
  "settings.cfNamedConfig": "命名隧道配置",
  "settings.configReady": "就绪",
  "settings.openLog": "打开日志",
  "settings.resetAddress": "重新生成地址",
  "settings.resetHint": "会使当前 URL 失效；所有客户端都需更新。",
  "settings.toolsHint": "Portal 有意只暴露命令与文件传输两类工具。",
  "settings.openVscodeSettings": "打开 VS Code 设置",
  "settings.settingsHint": "全部选项位于 portal.* 配置节。",
  "settings.copyInstall": "复制",

  "settings.ngrokConfigPath": "ngrok 配置文件（--config）",
  "settings.ngrokConfigPathHint": "ngrok 配置文件路径。让每个窗口指向不同文件，即可同时运行两个 ngrok 账号。",
  "settings.ngrokApiPort": "ngrok 检查接口端口（Portal 轮询用）",
  "settings.ngrokApiPortHint": "Portal 去哪个本地端口查询隧道列表。同时运行的 ngrok 不能共用端口，第二个会自动挪到 4041，所以给第二个窗口填 4041 可免掉等待。填 0 表示扫描 4040-4045 并按域名匹配。",

  "profile.sectionTitle": "连接配置档案",
  "profile.hint": "档案把隧道提供方、域名和 ngrok 账号打包在一起。列表全局共享；选中的档案保存在当前工作区，因此多个 VS Code 窗口可以同时使用不同档案。",
  "profile.empty": "还没有档案 —— 点击「新建档案」创建。",
  "profile.new": "新建档案",
  "profile.nameLabel": "档案名称",
  "profile.namePlaceholder": "例如：ngrok 账号 A",
  "profile.save": "保存",
  "profile.cancel": "取消",
  "profile.edit": "编辑",
  "profile.duplicate": "复制",
  "profile.delete": "删除",
  "profile.use": "使用",
  "profile.activeTag": "本工作区正在使用",
  "profile.editorTitle": "编辑档案",
  "profile.newTitle": "新建档案",
  "profile.defaultOption": "不使用档案（普通设置）",
  "profile.pickPlaceholder": "选择连接配置档案",
  "profile.noneDefined": "还没有定义任何连接配置档案。",
  "profile.saved": "档案“{0}”已保存。",
  "profile.deleted": "档案“{0}”已删除。",
  "profile.duplicated": "档案已复制为“{0}”。",
  "profile.nameRequired": "请填写档案名称。",
  "profile.nameDuplicate": "已存在同名档案。",
  "profile.switched": "当前档案：{0}",
  "profile.switchedRestart": "已切换到“{0}”。重启 Portal 后生效。",
  "profile.restartNow": "立即重启",
  "profile.noFolder": "当前没有打开工作区文件夹，选择已保存到全局并对所有窗口生效。",
  "profile.runningAs": "档案 {0}",
  "profile.runningDefault": "默认设置",
  "profile.stale": "当前运行的是“{0}”，已选择“{1}” —— 重启后生效。",

  "command.switchProfile": "Portal：切换连接配置档案...",
  "command.restart": "Portal：重启",
  "sidebar.profile": "档案",

  "sidebar.sessionPick": "选择侧边栏显示哪个 MCP 会话",

  "session.sectionTitle": "MCP 会话",
  "session.hint": "每个会话都是独立的 MCP 端点，拥有自己的路由令牌，并可选指定自己的工作区与隧道设置。会话并行运行；侧边栏选择显示哪一个。",
  "session.empty": "还没有会话 —— 点击「新建会话」创建。",
  "session.new": "新建会话",
  "session.idLabel": "会话 id",
  "session.labelLabel": "显示名称",
  "session.tokenLabel": "路由令牌",
  "session.tokenPlaceholder": "留空则自动生成",
  "session.workspaceLabel": "工作区路径（可选）",
  "session.editorTitle": "编辑会话",
  "session.newTitle": "新建会话",
  "session.saved": "会话“{0}”已保存。",
  "session.deleted": "会话“{0}”已删除。",
  "session.idRequired": "请填写会话 id。",
  "session.idDuplicate": "已存在相同 id 的会话。",
  "session.defaultLabel": "默认",

  "msg.pickToken": "选择 MCP 会话",
  "msg.tokenLabelTitle": "会话名称",
  "msg.tokenLabelPlaceholder": "例如：workspace-a",
  "msg.pickTokenRemove": "选择要移除的会话",
  "msg.tokenAdded": "Portal：已添加会话“{0}”。",

  "settings.section.agentInstructions": "Agent 提示词",
  "settings.agentInstructionsHint": "在 MCP `initialize` 时返回给客户端/Agent 的提示词。留空则使用 Portal 内置的默认提示词。下次启动 Portal 时生效。",
  "settings.agentInstructionsPlaceholder": "留空以使用 Portal 内置的默认提示词。",
  "settings.saveInstructions": "保存",

  "prompt.sectionTitle": "提示词",
  "prompt.hint": "预置包含链接的提示词：用 {url} 作占位符，复制时会替换为当前的公开 MCP 地址。",
  "prompt.nameLabel": "名称",
  "prompt.templateLabel": "模板",
  "prompt.namePlaceholder": "例如：给 Agent 的开工提示词",
  "prompt.templatePlaceholder": "连接 MCP 端点 {url}，然后……",
  "prompt.add": "添加",
  "prompt.update": "更新",
  "prompt.cancel": "取消",
  "prompt.copy": "复制",
  "prompt.edit": "编辑",
  "prompt.delete": "删除",
  "prompt.empty": "还没有提示词模板。",
  "prompt.copyTip": "连同实时链接一起复制",
  "prompt.needsUrl": "包含 {url}，启动后可用",
  "prompt.staticTip": "原样复制（无链接占位符）",

  "advice.openDocs": "打开文档",
  "advice.copySolution": "复制修复方案",
  "advice.solution": "修复",
};

export function isZh(): boolean {
  return (vscode.env.language || "en").toLowerCase().startsWith("zh");
}

export function localeTag(): string {
  return isZh() ? "zh-CN" : "en";
}

// Translate + printf-style interpolation, falling back to the key itself.
export function t(key: MsgKey | string, ...args: Array<string | number>): string {
  const table: Record<string, string> = isZh() ? ZH : EN;
  const fallback: Record<string, string> = EN;
  let s = table[key] ?? fallback[key] ?? key;
  return s.replace(/\{(\d+)\}/g, (_m, i) => String(args[Number(i)] ?? ""));
}

export function bundle(): Record<string, string> {
  return { ...(isZh() ? ZH : EN) };
}

// Injects window.__NB_L10N__ + a t() shim into the webview HTML.
export function webviewL10nScript(): string {
  return `const L10N = ${JSON.stringify(bundle())};
    const t = (k, ...a) => String(L10N[k] ?? k).replace(/\\{(\\d+)\\}/g, (_, i) => (a[i] ?? ''));`;
}
